Repository replicatedhq/replicated-field-labs, pull requests merged in 2023-06, with the labels that each got.

#271 Distributing Your Application with Replicated - Helm + Replicated SDK
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/check-shell
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/cleanup-shell
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/setup-shell
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/solve-shell
  instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
  instruqt/distributing-with-replicated/02-enabling-the-sdk/check-shell
  instruqt/distributing-with-replicated/02-enabling-the-sdk/cleanup-shell
  instruqt/distributing-with-replicated/02-enabling-the-sdk/setup-shell
  instruqt/distributing-with-replicated/02-enabling-the-sdk/solve-shell
  instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
  instruqt/distributing-with-replicated/03-creating-a-release/check-shell
  instruqt/distributing-with-replicated/03-creating-a-release/cleanup-shell
  instruqt/distributing-with-replicated/03-creating-a-release/solve-shell
  instruqt/distributing-with-replicated/04-installing-the-application/assignment.md
  instruqt/distributing-with-replicated/04-installing-the-application/check-shell
  instruqt/distributing-with-replicated/04-installing-the-application/cleanup-shell
  instruqt/distributing-with-replicated/04-installing-the-application/setup-cluster
  instruqt/distributing-with-replicated/04-installing-the-application/setup-shell
  instruqt/distributing-with-replicated/04-installing-the-application/solve-shell
  instruqt/distributing-with-replicated/05-validating-the-install/assignment.md
  instruqt/distributing-with-replicated/05-validating-the-install/cleanup-shell
  instruqt/distributing-with-replicated/assets/active-customer-in-channel.png
  instruqt/distributing-with-replicated/assets/adding-the-dependency.png
  instruqt/distributing-with-replicated/assets/bumping-the-version.png
  instruqt/distributing-with-replicated/assets/customers-page.png
  instruqt/distributing-with-replicated/assets/helm-install-instructions.png
  instruqt/distributing-with-replicated/assets/instance-details.png
  instruqt/distributing-with-replicated/assets/omozan-customer-page.png
  instruqt/distributing-with-replicated/assets/saving-your-changes.png
  instruqt/distributing-with-replicated/assets/single-customer-page.png
  instruqt/distributing-with-replicated/assets/stable-channel-customers.png
  instruqt/distributing-with-replicated/assets/vendor-portal-landing.png
  instruqt/distributing-with-replicated/config.yml
  instruqt/distributing-with-replicated/track.yml
  instruqt/distributing-with-replicated/track_scripts/setup-cluster
  instruqt/distributing-with-replicated/track_scripts/setup-shell
  instruqt/distributing-with-replicated/vendor/vendor.json
  libs/header.sh
Labels: type::feature

#272 Incorporates feedback from Dex's review
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
  instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
  instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
  instruqt/distributing-with-replicated/03-creating-a-release/check-shell
  instruqt/distributing-with-replicated/03-creating-a-release/solve-shell
  instruqt/distributing-with-replicated/04-installing-the-application/assignment.md
  instruqt/distributing-with-replicated/04-installing-the-application/solve-shell
  instruqt/distributing-with-replicated/05-validating-the-install/assignment.md
  instruqt/distributing-with-replicated/assets/active-customer-in-channel.png
  instruqt/distributing-with-replicated/assets/vendor-portal-landing.png
  instruqt/distributing-with-replicated/track.yml
Labels: type::bug, bug::normal

#274 Updates `CODEOWNERS`
  CODEOWNERS
Labels: type::chore

#273 Adds the "Avoiding Installation Pitfalls" lab
  docker/shell/Dockerfile
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/assignment.md
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/check-shell
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/cleanup-shell
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/setup-shell
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/solve-shell
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/assignment.md
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/check-shell
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/cleanup-shell
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/setup-cluster
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/solve-shell
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/assignment.md
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/check-shell
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/cleanup-shell
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/setup-shell
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/solve-shell
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/assignment.md
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/check-shell
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/cleanup-shell
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/solve-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/assignment.md
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/check-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/cleanup-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/assignment.md
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/check-shell
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/cleanup-shell
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/setup-cluster
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/setup-worker1
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/setup-worker2
  instruqt/avoiding-installation-pitfalls/assets/cpu-preflight-warning.png
  instruqt/avoiding-installation-pitfalls/assets/create-customer-button.png
  instruqt/avoiding-installation-pitfalls/assets/creating-harbor-preflights.png
  instruqt/avoiding-installation-pitfalls/assets/creating-the-preflights-template.png
  instruqt/avoiding-installation-pitfalls/assets/customer-preflight-checks-after.png
  instruqt/avoiding-installation-pitfalls/assets/customer-preflight-checks-before.png
  instruqt/avoiding-installation-pitfalls/assets/harbor-login-page.png
  instruqt/avoiding-installation-pitfalls/assets/install-instructions.png
  instruqt/avoiding-installation-pitfalls/assets/memory-preflight-failure.png
  instruqt/avoiding-installation-pitfalls/assets/new-customer-details.png
  instruqt/avoiding-installation-pitfalls/assets/passing-version-check.png
  instruqt/avoiding-installation-pitfalls/assets/saving-harbor-preflights.png
  instruqt/avoiding-installation-pitfalls/assets/saving-the-preflights-template.png
  instruqt/avoiding-installation-pitfalls/assets/vendor-portal-landing.png
  instruqt/avoiding-installation-pitfalls/config.yml
  instruqt/avoiding-installation-pitfalls/track.yml
  instruqt/avoiding-installation-pitfalls/track_scripts/setup-cluster
  instruqt/avoiding-installation-pitfalls/track_scripts/setup-shell
  instruqt/avoiding-installation-pitfalls/vendor/vendor.json
  libs/header.sh
Labels: type::feature

#276 Repairs small defects in preflights lab
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/assignment.md
  instruqt/avoiding-installation-pitfalls/track.yml
Labels: type::bug, bug::normal

#278 fix: Add missing customer email to Instruqt variables in "Avoiding Installation Pitfalls" lab
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
Labels: type::bug, bug::normal

#279 Fixes based on feedback from Builders Plan run throughs
  instruqt/avoiding-installation-pitfalls/01-working-with-preflight-checks/cleanup-shell
  instruqt/avoiding-installation-pitfalls/02-checking-cluster-resources/cleanup-shell
  instruqt/avoiding-installation-pitfalls/03-adding-preflights-to-the-chart/cleanup-shell
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/cleanup-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/cleanup-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/assignment.md
  instruqt/avoiding-installation-pitfalls/06-completing-the-install/cleanup-shell
  instruqt/avoiding-installation-pitfalls/track.yml
  instruqt/distributing-with-replicated/04-installing-the-application/assignment.md
Labels: type::bug, bug::normal
