Repository replicatedhq/replicated-field-labs, pull requests merged in 2023-07, with the labels that each got.

#283 Enables labs to run with a Builders Plan only team
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/setup-shell
  instruqt/avoiding-installation-pitfalls/05-validating-before-an-install/solve-shell
  instruqt/avoiding-installation-pitfalls/track.yml
  instruqt/closing-information-gap/01-viewing-instance-info/assignment.md
  instruqt/closing-information-gap/06-support-bundle-diagnosis/setup-shell
  instruqt/closing-information-gap/track.yml
  instruqt/closing-information-gap/track_scripts/setup-shell
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
  instruqt/distributing-with-replicated/04-installing-the-application/setup-shell
  instruqt/distributing-with-replicated/track.yml
Labels: type::chore

#282 Updates for Harbor and SDK version bumps
  instruqt/avoiding-installation-pitfalls/track_scripts/setup-shell
  instruqt/closing-information-gap/track_scripts/setup-shell
  instruqt/distributing-with-replicated/01-preparing-to-use-the-sdk/assignment.md
  instruqt/distributing-with-replicated/02-enabling-the-sdk/assignment.md
  instruqt/distributing-with-replicated/02-enabling-the-sdk/solve-shell
  instruqt/distributing-with-replicated/track.yml
Labels: type::chore

#293 Fixes release promotion instructions
  instruqt/avoiding-installation-pitfalls/04-releasing-the-application/assignment.md
  instruqt/avoiding-installation-pitfalls/track.yml
  instruqt/closing-information-gap/05-releasing-an-update/assignment.md
  instruqt/closing-information-gap/track.yml
  instruqt/distributing-with-replicated/03-creating-a-release/assignment.md
  instruqt/distributing-with-replicated/track.yml
Labels: type::bug, bug::regression

#292 Update check-shell - fix another typo
  instruqt/closing-information-gap/04-adding-to-the-chart/check-shell
Labels: type::bug, bug::normal

#304 compatibility matrix lab
  instruqt/compatibility-matrix/01-compatibility-matrix-basics/assignment.md
  instruqt/compatibility-matrix/config.yml
  instruqt/compatibility-matrix/track.yml
  instruqt/compatibility-matrix/track_scripts/setup-cluster
  instruqt/compatibility-matrix/track_scripts/setup-shell
  instruqt/validating-compatibility/01-basics/assignment.md
  instruqt/validating-compatibility/01-basics/check-shell
  instruqt/validating-compatibility/01-basics/cleanup-shell
  instruqt/validating-compatibility/01-basics/setup-shell
  instruqt/validating-compatibility/01-basics/solve-shell
  instruqt/validating-compatibility/02-troubleshooting/assignment.md
  instruqt/validating-compatibility/02-troubleshooting/check-shell
  instruqt/validating-compatibility/02-troubleshooting/cleanup-shell
  instruqt/validating-compatibility/02-troubleshooting/setup-shell
  instruqt/validating-compatibility/02-troubleshooting/solve-shell
  instruqt/validating-compatibility/03-testing/assignment.md
  instruqt/validating-compatibility/03-testing/check-shell
  instruqt/validating-compatibility/03-testing/cleanup-shell
  instruqt/validating-compatibility/03-testing/setup-shell
  instruqt/validating-compatibility/03-testing/solve-shell
  instruqt/validating-compatibility/config.yml
  instruqt/validating-compatibility/track.yml
  instruqt/validating-compatibility/track_scripts/setup-cluster
  instruqt/validating-compatibility/track_scripts/setup-shell
  instruqt/validating-compatibility/vendor/vendor.json
Labels: type::feature

#228 Provides a template for preserving the shell across challenges
  instruqt/shared-env-template/01-getting-to-know-the-template/assignment.md
  instruqt/shared-env-template/01-getting-to-know-the-template/check-shell
  instruqt/shared-env-template/01-getting-to-know-the-template/cleanup-shell
  instruqt/shared-env-template/01-getting-to-know-the-template/setup-shell
  instruqt/shared-env-template/01-getting-to-know-the-template/solve-shell
  instruqt/shared-env-template/02-using-the-template/assignment.md
  instruqt/shared-env-template/02-using-the-template/check-shell
  instruqt/shared-env-template/02-using-the-template/cleanup-shell
  instruqt/shared-env-template/02-using-the-template/solve-shell
  instruqt/shared-env-template/03-tips-and-tricks/assignment.md
  instruqt/shared-env-template/config.yml
  instruqt/shared-env-template/track.yml
  instruqt/shared-env-template/track_scripts/setup-cluster
  instruqt/shared-env-template/track_scripts/setup-shell
Labels: type::feature
