Repository replicatedhq/replicated-field-labs, pull requests merged in 2024-05, with the labels that each got.

#327 Protecting Your Assets with Replicated
  instruqt/protecting-your-assets/01-the-replicated-license/assignment.md
  instruqt/protecting-your-assets/01-the-replicated-license/check-shell
  instruqt/protecting-your-assets/01-the-replicated-license/setup-shell
  instruqt/protecting-your-assets/01-the-replicated-license/solve-shell
  instruqt/protecting-your-assets/01-validate-connectivity/assignment.md
  instruqt/protecting-your-assets/02-create-a-customer/assignment.md
  instruqt/protecting-your-assets/02-create-a-customer/check-shell
  instruqt/protecting-your-assets/02-create-a-customer/cleanup-shell
  instruqt/protecting-your-assets/02-create-a-customer/setup-shell
  instruqt/protecting-your-assets/02-create-a-customer/solve-shell
  instruqt/protecting-your-assets/03-proxying-private-images/assignment.md
  instruqt/protecting-your-assets/03-proxying-private-images/check-shell
  instruqt/protecting-your-assets/03-proxying-private-images/cleanup-shell
  instruqt/protecting-your-assets/03-proxying-private-images/setup-shell
  instruqt/protecting-your-assets/03-proxying-private-images/solve-shell
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/assignment.md
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/check-cluster
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/check-shell
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/cleanup-shell
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/setup-cluster
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/setup-shell
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/solve-shell
  instruqt/protecting-your-assets/05-license-entitlements/assignment.md
  instruqt/protecting-your-assets/05-license-entitlements/check-shell
  instruqt/protecting-your-assets/05-license-entitlements/solve-shell
  instruqt/protecting-your-assets/06-validating-license-fields/assignment.md
  instruqt/protecting-your-assets/06-validating-license-fields/check-shell
  instruqt/protecting-your-assets/06-validating-license-fields/cleanup-cluster
  instruqt/protecting-your-assets/06-validating-license-fields/cleanup-shell
  instruqt/protecting-your-assets/06-validating-license-fields/setup-shell
  instruqt/protecting-your-assets/06-validating-license-fields/solve-shell
  instruqt/protecting-your-assets/07-entitlement-metrics/assignment.md
  instruqt/protecting-your-assets/07-entitlement-metrics/check-shell
  instruqt/protecting-your-assets/07-entitlement-metrics/cleanup-cluster
  instruqt/protecting-your-assets/07-entitlement-metrics/cleanup-shell
  instruqt/protecting-your-assets/07-entitlement-metrics/setup-shell
  instruqt/protecting-your-assets/07-entitlement-metrics/solve-shell
  instruqt/protecting-your-assets/assets/create-a-license-field.png
  instruqt/protecting-your-assets/assets/create-customer-button.png
  instruqt/protecting-your-assets/assets/creating-the-image-pull-secret.png
  instruqt/protecting-your-assets/assets/customer-landing-page.png
  instruqt/protecting-your-assets/assets/editing-the-deployment.png
  instruqt/protecting-your-assets/assets/helm-login-command.png
  instruqt/protecting-your-assets/assets/image-values.png
  instruqt/protecting-your-assets/assets/managing-images.png
  instruqt/protecting-your-assets/assets/member-count-field.png
  instruqt/protecting-your-assets/assets/new-customer-details.png
  instruqt/protecting-your-assets/assets/opening-the-license-file.png
  instruqt/protecting-your-assets/assets/signature-verification-info.png
  instruqt/protecting-your-assets/assets/updating-entitlements.png
  instruqt/protecting-your-assets/assets/user-metrics-events.png
  instruqt/protecting-your-assets/assets/user-metrics-for-instance.png
  instruqt/protecting-your-assets/assets/vendor-portal-landing.png
  instruqt/protecting-your-assets/config.yml
  instruqt/protecting-your-assets/track.yml
  instruqt/protecting-your-assets/track_scripts/setup-cluster
  instruqt/protecting-your-assets/track_scripts/setup-shell
  instruqt/track-slugs.yml
  setup/pkg/fieldlabs/policy.go
Labels: type::feature

#334 update checkout action to v4
  .github/workflows/build-jumpbox-image.yaml
  .github/workflows/build-shell-image.yaml
  .github/workflows/instruqt-create-dev-track.yml
  .github/workflows/instruqt-dev-track-test.yml
  .github/workflows/instruqt-generate-track-slugs.yml
  .github/workflows/instruqt-prod-track-test.yml
  .github/workflows/instruqt-promote-dev-track.yml
Labels: type::chore

#340 Typo fixes in step 1
  instruqt/protecting-your-assets/01-the-replicated-license/assignment.md
Labels: type::chore

#342 Other typos/minor edits
  instruqt/protecting-your-assets/02-create-a-customer/assignment.md
  instruqt/protecting-your-assets/03-proxying-private-images/assignment.md
  instruqt/protecting-your-assets/04-helm-values-for-license-fields/assignment.md
  instruqt/protecting-your-assets/05-license-entitlements/assignment.md
  instruqt/protecting-your-assets/06-validating-license-fields/assignment.md
Labels: type::chore

#337 Troubleshoot Training with EC
  .gitignore
  instruqt/troubleshoot-training/01-introduction/assignment.md
  instruqt/troubleshoot-training/01-introduction/check-cloud-client
  instruqt/troubleshoot-training/01-introduction/solve-cloud-client
  instruqt/troubleshoot-training/02-troubleshoot-1/assignment.md
  instruqt/troubleshoot-training/02-troubleshoot-1/check-cloud-client
  instruqt/troubleshoot-training/02-troubleshoot-1/setup-cloud-client
  instruqt/troubleshoot-training/02-troubleshoot-1/solve-cloud-client
  instruqt/troubleshoot-training/03-troubleshoot-2/assignment.md
  instruqt/troubleshoot-training/03-troubleshoot-2/check-cloud-client
  instruqt/troubleshoot-training/03-troubleshoot-2/setup-cloud-client
  instruqt/troubleshoot-training/03-troubleshoot-2/solve-cloud-client
  instruqt/troubleshoot-training/04-troubleshoot-3/assignment.md
  instruqt/troubleshoot-training/04-troubleshoot-3/check-cloud-client
  instruqt/troubleshoot-training/04-troubleshoot-3/setup-cloud-client
  instruqt/troubleshoot-training/04-troubleshoot-3/solve-cloud-client
  instruqt/troubleshoot-training/05-troubleshoot-4/assignment.md
  instruqt/troubleshoot-training/05-troubleshoot-4/check-cloud-client
  instruqt/troubleshoot-training/05-troubleshoot-4/setup-cloud-client
  instruqt/troubleshoot-training/05-troubleshoot-4/solve-cloud-client
  instruqt/troubleshoot-training/06-troubleshoot-5/assignment.md
  instruqt/troubleshoot-training/06-troubleshoot-5/check-cloud-client
  instruqt/troubleshoot-training/06-troubleshoot-5/setup-cloud-client
  instruqt/troubleshoot-training/06-troubleshoot-5/solve-cloud-client
  instruqt/troubleshoot-training/07-support-bundle-types/assignment.md
  instruqt/troubleshoot-training/08-super-secret/assignment.md
  instruqt/troubleshoot-training/assets/deploy.png
  instruqt/troubleshoot-training/assets/services-explained.png
  instruqt/troubleshoot-training/config.yml
  instruqt/troubleshoot-training/track.yml
  instruqt/troubleshoot-training/track_scripts/setup-cloud-client
Labels: type::feature

#343 fix a typo causing the track to crash
  instruqt/troubleshoot-training/track.yml
  instruqt/troubleshoot-training/track_scripts/setup-cloud-client
Labels: type::bug, echoes/effort: XS
